Added Form, Form test, and Form story for Staff component
ucsb-cs156-s24/proj-organic-s24-5pm-2 pull request #10
Opened 2024-05-20 23:55 UTC by richardfang888

- Created \frontend\src\main\components\Staff\StaffForm.js which creates the Staff Form according to the existing db entity and fixture
- Created test for the StaffForm in \frontend\src\tests\components\Staff\StaffForm.test.js
- Created story for the StaffForm in \frontend\src\stories\components\School\SchoolForm.stories.js

Closes #9

2024-05-23 03:40 UTC, pconrad requested changes
* Please see my comments on the team slack channel about PR descriptions and update this one accordingly.
* Please also update the issue to which this links by filling in the description (currently totally blank) and adding acceptance crtiera.
* Please also address the other concerns in the CR below.

2024-05-23 03:40 UTC, pconrad commented on frontend/src/main/components/Staff/StaffForm.js
> +export default StaffForm;
I think the only thing we want on this form is literally GithubId and a submit button and literally nothing else.

The form will be embedded on a page where the course id is already there.   We'll use that information to send the add to the backend.

2024-05-28 04:19 UTC, pconrad requested changes

2024-05-28 04:19 UTC, pconrad commented on frontend/src/main/components/Staff/StaffForm.js
> +  // const githubId_regex = '';
It's not clear what the intentions of these comments are.  
Can we remove them?

2024-05-28 04:33 UTC, pconrad requested changes
Please review the comments on the team slack channel here:
https://ucsb-cs156-s24.slack.com/archives/C06SC553MLY/p1716870268080979

And see if this needs any reworking.

Adding staff should always be done in the context of a course.

Someone is a TA or an LA *for a specific course*. They are not an LA or TA "in general".

So the form for adding a staff member needs to have the information about the course right on the page, so that we know which course we are adding a TA or LA to.

I would suggest that the URL should contain the id of the course and the information about that course should be displayed at the top of the page.

I would suggest, actually not even HAVING a separate page for adding staff. Instead, it should go on the course show page.   And there is no need for edit.  Only add and delete.

2024-05-28 06:17 UTC, richardfang888 commented
> Please review the comments on the team slack channel here: https://ucsb-cs156-s24.slack.com/archives/C06SC553MLY/p1716870268080979
> 
> And see if this needs any reworking.
> 
> Adding staff should always be done in the context of a course.
> 
> Someone is a TA or an LA _for a specific course_. They are not an LA or TA "in general".
> 
> So the form for adding a staff member needs to have the information about the course right on the page, so that we know which course we are adding a TA or LA to.
> 
> I would suggest that the URL should contain the id of the course and the information about that course should be displayed at the top of the page.
> 
> I would suggest, actually not even HAVING a separate page for adding staff. Instead, it should go on the course show page. And there is no need for edit. Only add and delete.

I think I have addressed these changes in my most recent commit by making courseId implicit in the form and displayed alongside the id. I have adjusted the tests for the form as well.

2024-05-28 21:16 UTC, abhishekambastha04 approved these changes
LGTM

2024-05-28 22:22 UTC, NevMan1 approved these changes
LGTM

2024-05-30 00:54 UTC, andrewpengucsb approved these changes
LGTM

2024-05-30 00:57 UTC, merged