Nico - Updated Backend to Spring Boot 3
ucsb-cs156-s24/proj-organic-s24-5pm-2 pull request #12
Opened 2024-05-22 01:24 UTC by nicoshinozaki

In this PR, we upgrade the backend to Spring Boot 3.

Deployed at: http://organic-nicoshinozaki-dev.dokku-10.cs.ucsb.edu

Closes #8

2024-05-23 03:53 UTC, pconrad requested changes
LGTM except for a couple of things:
* Please update the description
* Please remove some commented out code.
* Please deploy to a dokku dev instance and link to the deployed instance in the PR description.  This is extra important because of the fact that we don't yet have full integration and end2end tests in this code base yet, and so the only way to know that we didn't break anything is to test it manually.
* Please consider making the change that Daniel Jensen suggested on the slack <https://ucsb-cs156-s24.slack.com/archives/C074MLEP1QD/p1716436359312639>

2024-05-23 03:53 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/config/SecurityConfig.java
>    // private LoginSuccessHandler loginSuccessHandler;
Please remove the commented out code (yes, I know it was in the original, but the rule is, if you touch the file, you have to clean it up.)

2024-05-24 00:57 UTC, abhishekambastha04 approved these changes
LGTM

2024-05-25 03:56 UTC, pconrad approved these changes
LGTM!

2024-05-25 03:58 UTC, merged