Abhishek - H2 Console
ucsb-cs156-s24/proj-organic-s24-5pm-2 pull request #14
Opened 2024-05-22 01:39 UTC by abhishekambastha04

This closes #11
This adds an H2 console option on the navbar.

2024-05-23 03:55 UTC, pconrad requested changes
Some commented out code and superflous comments to look at

2024-05-23 03:55 UTC, pconrad commented on src/main/resources/application-development.properties
> +#spring.h2.console.enabled=true
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-23 03:55 UTC, pconrad commented on src/main/resources/application-development.properties
> +#app.showSwaggerUILink=true
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-23 03:55 UTC, pconrad commented on src/main/resources/application-production.properties
> +# next line adds to UIlink
```suggestion
```

Comment seems superfluous here... this file is pretty self-explanatory.

2024-05-23 03:55 UTC, pconrad commented on src/main/resources/application-production.properties
> +#next line adds the H2 console option
```suggestion
```
Comment seems superfluous here... this file is pretty self-explanatory.

2024-05-24 00:47 UTC, NevMan1 submitted a review, later dismissed
LGTM

2024-05-27 18:24 UTC, merged