Created Prefix matching, Autocomplete, and typing mode for dropdown menu
ucsb-cs156-s24/proj-organic-s24-5pm-2 pull request #35
Opened 2024-05-28 20:58 UTC by ukyl

### Changes

---

In this PR we updated the generic dropdown menu to allow the User to 

1. type in the content they want (in addition to selecting from a dropdown)
2. autocomplete their query by pressing `Enter`
3. minimise their search by limiting the shown content to only those with a matching prefix

As a User I can type and see whether or not my query is invalid:
![invalid](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/assets/53740464/bc2d86f9-985d-4163-bec3-fdcbb2ced151)

As a user I can limit my query through prefixes:
![dropdownprefixsimple](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/assets/53740464/5607af4e-3b2e-42d5-9674-a1394e0e9405)

As a user I can finish my dropdown selection with Enter:
![autocomplete](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/assets/53740464/7ed554dd-084d-46e7-bb36-63f8e5d7eb10)

### Issues

Link to storybook

---
Partially closes #2 
Closes #34

2024-05-29 00:32 UTC, NevMan1 approved these changes, later dismissed
LGTM

2024-05-30 00:16 UTC, nicoshinozaki approved these changes, later dismissed
LGTM

2024-05-30 16:30 UTC, pconrad requested changes
This is really nice work.   But I wonder if it would be better to do one of two things:
* EITHER: Create two different components: `<OurAddDropdownForm>` which has the previous behavior and a new one `<OurAutocompleteForm>` that has the new behavior?
* OR: Keep just one component, but have an option on it so that `<OurAddDropdownForm>` behaves as it did before, but `<OurAddDropdownForm autocomplete={true}>` has the new behavior? 

There are use cases for both, so I think it would be helpful to give future developers the choice, since you've put so much work into this.

2024-05-30 18:14 UTC, ukyl commented
> This is really nice work. But I wonder if it would be better to do one of two things:
> 
> * EITHER: Create two different components: `<OurAddDropdownForm>` which has the previous behavior and a new one `<OurAutocompleteForm>` that has the new behavior?
> * OR: Keep just one component, but have an option on it so that `<OurAddDropdownForm>` behaves as it did before, but `<OurAddDropdownForm autocomplete={true}>` has the new behavior?
> 
> There are use cases for both, so I think it would be helpful to give future developers the choice, since you've put so much work into this.

I've switched it to be one component of having the option of `autocomplete={true}`

2024-06-05 22:01 UTC, merged